server:
    port: 9092
spring:
  jpa:
      show-sql: false
      open-in-view: false
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  mail:
      host: smtp.gmail.com
      port: 587
      username:
      password:
      protocol: smtp
      tls: true
      properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
  datasource :
      url: jdbc:mysql://localhost:3306/danhgia24h?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username : root
      password :
  messages:
      basename: i18n/messages
      cache-seconds: -1
      encoding: UTF-8
logging:
    pattern:
      level: "%X{mdcData}%5p"

security:
  basic:
    enabled: false
#management.security.enabled=false

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: http://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
    http:
        version: V_1_1 # To use HTTP/2 you will need SSL support (see above the "server.ssl" configuration)
    cache: # Cache configuration
        ehcache: # Ehcache configuration
            time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
            max-entries: 100 # Number of objects in each cache entry
    # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
    cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization"
        allow-credentials: true
        max-age: 1800
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: erp@localhost
        base-url: http://127.0.0.1:8080
application:
    activation:
      expirePeriod: 86400 #milliseconds
      enableMail: false #true/false
    ldap:
      enabled: false #true/false
      url: ldap://172.24.104.10:389
      base: dc=vnpt-technology,dc=vn
      userDN: ssdclab@vnpt-technology.vn
      password: Ssdc123!
